### ISSUE TITLE
This plugin need a version tag

### ISSUE THREAD

**Issue by gitbenb** [chrismou/phergie-irc-plugin-react-google#1]
currently unable to use composer.json like this with this plugin

 {
    "minimum-stability": "dev",
    "require": {
        "phergie/phergie-irc-bot-react":  "~1",
        "phergie/phergie-irc-plugin-react-pong": "~1",
        "phergie/phergie-irc-plugin-react-feedticker": "~1",
        "phergie/phergie-irc-plugin-react-commandhelp": "~1",
        "chrismou/phergie-irc-plugin-react-google": "~1",
        "chrismou/phergie-irc-plugin-react-audioscrobbler": "~1",
        "phergie/phergie-irc-plugin-react-nickserv": "~1",
        "phergie/phergie-irc-plugin-react-quit": "~1",
        "phergie/phergie-irc-plugin-react-thefuckingweather": "~1",
        "chrismou/phergie-irc-plugin-react-weather": "~1",
        "phergie/phergie-irc-plugin-react-youtube": "~1",
        "phergie/phergie-irc-plugin-react-autojoin": "~1",
        "phergie/phergie-irc-plugin-react-twitter": "~1",
        "phergie/phergie-irc-plugin-react-joinpart": "~1"
    }
}

output this : 
Problem 1
    - The requested package chrismou/phergie-irc-plugin-react-google could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package chrismou/phergie-irc-plugin-react-audioscrobbler could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package chrismou/phergie-irc-plugin-react-weather could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package phergie/phergie-irc-plugin-react-twitter could not be found in any version, there may be a typo in the package name.

**Comment by chrismou** [comment]
Hi Ben

The plugin (plus the weather & audioscrobbler plugins) are stable, but there's still a few tweaks I want to make before I tag them.

As per the installation instructions, if you set the version to dev-master (instead of ~1) they should work.  I'm using all 3 without any problems.

I'll leave this ticket open so you get a notification once they're tagged.  I'll also update the installation instructions when this is done.

**Comment by chrismou** [comment]
These 3 repos should all now be tagged as 1.0.0 and the installation instructions updated.  You should now be OK switching your require lines to reference ~1, if you want to :-)
